[build]
command = "npm --prefix frontend install && npm --prefix frontend run build"
publish = "frontend/dist"

[build.environment]
VITE_API_BASE_URL = "https://fleet-management-systerm.onrender.com/api/v1"

[[redirects]]
from = "/assets/*"
to = "/assets/:splat"
status = 200

[[redirects]]
from = "/script.js"
to = "/script.js"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
